version: '3'

services:
  discord-secure:
    build: .
    image: discord-flask:latest
    ports:
      - "5000:5000"
    environment: # set them in docker environment
      - bot_token=${DISCORD_BOT_TOKEN}
      - enc_key=${ENCRYPTION_KEY}
    volumes:
      - ./Data:/app/Data